train:
  data_dir: data
  data_split: 0.9
  model_file_dir: data/model_dir
  data_file_name: flower_photos.tgz
  base_url: https://storage.googleapis.com/download.tensorflow.org/example_images/

predict:
  test_img_path: d:/oneNeuron/Source/tflite_testing/daisy.jpeg 
  label_map:
    0: daisy 
    1: dandelion 
    2: roses
    3: sunflowers 
    4: tulips